services:
  db:
    image: postgres:17-alpine
    container_name: ejemploPrisma-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Chubaca2025
      POSTGRES_DB: ejemploPrisma
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ejemploPrisma-app
    command: sh -c "yarn prisma generate && yarn start:dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Chubaca2025@db:5432/ejemploPrisma?schema=public
    depends_on:
      - db

volumes:
  db_data:
